### ISSUE TITLE
city defence 2.0

### ISSUE THREAD

**Issue by Dorbedo** [Dorbedo/Operation_Kerberos#34]
completely dynamically created

**features**
- units in buildings
- statics in buildings
- roadblocks
- trip-wired doors
- IED's
- intelligent placed minefields

**tasks**
- [x] spawning units in city **SQF**
- [x] units patrol their buildings **SQF**
- [x] spawning static defense **SQF**
- [x] spawning roadblocks **SQF**
- [x] spawning civillian cars in garages **SQF**
- [x] spawning civillian cars roadside **SQF**
- [x] spawning mines **SQF**
- [x] spawning IEDs **SQF**
- [ ] spawning vehicle patrols **SQF**
- [x] spawning infantry patrols **SQF**
- [ ] generating spawn-position (best locations, best direction) **SQF**
- [x] generating roadblock (search for key Areas, main-Roads preferred) **SQF**
- [x] mines/IED-locations including tiggerman positions **SQF**
- [x] generate infantry patrols way points **SQF**
- [ ] generate vehicle patrols way points **SQF**
- [ ] generate areas for mission-objects or defence positions **SQF**
- [x] macro - list with defense positions **SQF**
- [x] spawn macro **SQF**

**reqiurements**
- buildinglist including (spawnpositons of infanterie, statics; positions of doors; )
- roads (mainroads, sideroads)

**Comment by Dorbedo** [comment]
Moved CPP part into City 3.0 #38

**Comment by Dorbedo** [comment]
69826e3fbbc7c535f8b5a63e2671c60ab6ef6399

**Comment by Dorbedo** [comment]
closed
