### ISSUE TITLE
city defence 3.0

### ISSUE THREAD

**Issue by Dorbedo** [Dorbedo/Operation_Kerberos#38]
improvement of city 2.0

**features**
- units in buildings
- statics in buildings
- cover the best area (surrounding Area depending)
- road spawns and building spawn are generated together
- roadblocks
- trip-wired doors
- IED's
- intelligent placed minefields

**tasks**
- [x] export function for buildings-list **SQF**
- [ ] extensionhandling function **SQF**
- [ ] generate surface grid **SQF**
- [ ] predefined fortified buildings **HPP**
- [ ] predefined roadblocks **HPP**
- [ ] export function for fortified buildings **SQF**
- [ ] export function for roadblocks **SQF**
- [ ] spawn predefined fortififications **SQF**
- [ ] generate IED-Locations **CPP**
- [ ] generate Infaterie locations **CPP**
- [ ] generate Inf - Patrols **CPP**
- [ ] generate Veh - patrols **CPP**
- [ ] generate spawnlocations of civ-vehicles **CPP**
- [ ] generate defence-positions and weight them **CPP**
- [ ] generate roadblocks (including checking sourrounding Area **CPP**
- [ ] roadblocks are supported by sourrounding buildings **CPP**
- [ ] gernerate location of IEDs with triggerman **CPP**
- [ ] spawn IED with triggerman **SQF**
- [ ] spawning units **SQF**
- [ ] spawning patrols **SQF**
- [ ] spawning vehicles **SQF**
- [ ] spawning roadblock-items **SQF**
- [ ] generate objective-locations **CPP**
- [ ] generate location of important fortfications (AA-Pos, Commander, ....) **CPP**
- [ ] check important locations **SQF**
- [ ] spawn important fortifications **SQF**

**Comment by Dorbedo** [comment]
declined
